### ISSUE TITLE
[External] GetResponseStream

### ISSUE THREAD

**Issue by eknraw** [Microsoft/cal-open-library#105]
Would this function in CU1297 ever be made external? 

[https://github.com/Microsoft/cal-open-library/blob/5d5974c81878e816ab60841da9cbfbd71dd9c77a/BaseApp/COD1297.TXT#L36](https://github.com/Microsoft/cal-open-library/blob/5d5974c81878e816ab60841da9cbfbd71dd9c77a/BaseApp/COD1297.TXT#L36)

Thanks!

**Comment by JesperSchulz** [comment]
Sorry for the late reply! You can get a wrapped version of the response stream from the built-in Http functionality in the al language. Unless you have a special scenario you should be covered and will not need this function to be made external. Do you have a special scenario we didn't think of?
