### ISSUE TITLE
Request for SQLCommand or extend the Query object

### ISSUE THREAD

**Issue by mboon75** [microsoft/cal-open-library#116]
In the current NAV 2018 on-premises we make use of SQL Command to produce high performing queries and more flexible queries than the current NAV Table and Query objects allow us. 
Typical TSQL commands we use are 
- Like statement
- More sophisticated OR statements
- inner join 
- cross apply
- union
- Date formula's
- Intermediate results in TempTables.
- Join over different companies

If we want the current functionality written 100% using C/AL code, we have super bad performance, because it will end up in more and more sub queries and nested loops.

**Comment by systema365** [comment]
I agree.  This or expand the "Query" object to facilitate more advanced queries.

**Comment by JesperSchulz** [comment]
Sounds like a great idea! Could I ask either of you to post that idea to to [Business Central - Ideas](http://aka.ms/bcideas)? You'll have better luck getting it implemented and noticed by other partners if you post it there, as this GitHub repository only handles issues regarding our set of library functions in (C/)AL.

**Comment by mboon75** [comment]
Done:
https://experience.dynamics.com/ideas/idea/?ideaid=972a4dde-fc90-e911-80e7-0003ff68e84c

**Comment by JesperSchulz** [comment]
Great! Thanks :) Now let's hope for a lot of votes to get this pushed up in the backlog!
