### ISSUE TITLE
Missing dotnet wrappers in the Codeunits in the 3000 range

### ISSUE THREAD

**Issue by monicasuica** [microsoft/cal-open-library#121]
Missing dotnet in the codeunits in the 3000 range:
System.IO.FileStream.'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
System.IO.FileMode.'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Missing functions in existing 3000:*
cu3026 DotNet_Encoding: Encoding.BigEndianUnicode; Encoding := Encoding.UTF7;
cu3008 DotNet_Convert: Convert.ToInt32(Hex,16)

Can the codeunits in the range 3000 be extended with libraries and functions added above?

Thank you.

**Comment by JesperSchulz** [comment]
We're looking into alternative solutions to the dotnet wrapper codeunits and will not be adding any new ones right now. However, if you create a PR in this repo, we'll consider your suggestions while looking at those solutions.
