### ISSUE TITLE
Please add Add* methods to codeunit 3003 DotNet_DateTime

### ISSUE THREAD

**Issue by jhoek** [microsoft/cal-open-library#122]
DateTimes in .NET support several Add* methods, e.g. AddDays, AddHours etc. It would be great to have these in the wrapper codeunit as well, especially since there's also no native C/SIDE way to manipulate datetimes like this that I'm aware of. Thanks for considering!

**Comment by JesperSchulz** [comment]
We're looking into alternative solutions to the dotnet wrapper codeunits and will not be adding any new ones right now. However, if you create a PR in this repo, we'll consider your suggestions while looking at those solutions.
