### ISSUE TITLE
Please add ISO-8859-1 method to codeunit 3026 DotNet_Encoding

### ISSUE THREAD

**Issue by MattiLE** [microsoft/cal-open-library#123]
Hi, could you add the following method: 

[External] ISO88591()
DotNetEncoding := DotNetEncoding.GetEncoding('iso-8859-1');

It would be great if the function were present in the codeunit. This would no longer require a DotNet variable in my calling object. 

Thank you!

**Comment by JesperSchulz** [comment]
Sure. We'll look into it. Expect the function to be part of the next major release in the fall.
