### ISSUE TITLE
how to proceed Codeunit 3031 DotNet_SmtpMessage

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/cal-open-library#126]
Dear,

about: OBJECT Codeunit 3031 DotNet_SmtpMessage

this wrapper is still based on the Microsoft.Dynamics.Nav.SMTP. **Why?** 
We already created in NAV a codeunit our shelves based on 
System.Net.Mail.SmtpClient.'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' 
and 
System.Net.Mail.MailMessage.'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

makes a NAV dll less and there are more possibilities .

But the actual problem is this, we need the Alternative view on the MailMessage. 
**why?** Because without it NAV scores very high in the spam filtering rate when mailing because there is no possibility when adding a HTML body, to also add the plain text body as extra view. which is required to score less high as potential spammer.

the difference is a full 1 point on the spam score!

I cannot contribute to the OBJECT Codeunit 3031 DotNet_SmtpMessage because the DotNet Microsoft.Dynamics.Nav.SMTP does not have the alternative view exposed of the dotnet MailMessage.

![image](https://user-images.githubusercontent.com/48794854/61529070-b393e400-aa20-11e9-968d-a5e281f418a9.png)

What to do now? should i add a whole new 3000 SMTP codeunit based on the actual dotnet framework? (will probably be refused) or may i rewrite this codeunit to the actual dotnet framework? or can Alternative view be added in the Microsoft.Dynamics.Nav.SMTP dll? 

else this wrapper is worthless because of high spam rate.

Awaiting your request.

**Comment by JesperSchulz** [comment]
Changing to System.Net.Mail would also do no good, as that one is deprecated: https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.8.

We are currently working on retireing Microsoft.Dynamics.Nav.SMTP, replacing it by MailKit. We should be ready in time for next major release (and will most likely backport the change). Hence, you need to do nothing right now :-) We've got it covered!
