### ISSUE TITLE
Codeunit 1297 "Http Web Request Mgt." outdated in Code and could function ProcessFaultJsonResponse be global

### ISSUE THREAD

**Issue by SjoerddeClippelaar** [microsoft/cal-open-library#128]
Hello,

I would like the function ProcessFaultJsonResponse in the codeunit 1297 to be global, but when checking the repository online I saw it differs from the NAVW114.00 version of the codeunit and doesn't contain the function.

![Codeunit](https://user-images.githubusercontent.com/50202846/61869023-f94a2400-aeda-11e9-8593-d14de5a3e938.png)

Will you still be supporting this codeunit?
Would it be possible to make the function ProcessFaultJsonResponse global?
How could we create a pull request in the future for this kind of changes?

Dear regards,

Sjoerd de Clippelaar
Mysolution BV

**Comment by JesperSchulz** [comment]
I just checked in our upcoming major release, where the function is present. This repository is out of sync, as we're looking into retireing it and merging it into our https://github.com/Microsoft/alappextensions repo. Once we've merged the repositories, there should be clear instructions on how to create PRs.
For now, I will make the function public in the upcoming major.

**Comment by SjoerddeClippelaar** [comment]
Could you do the same for the GetResponseJson in codeunit 1297?

**Comment by JesperSchulz** [comment]
Sure :-)

**Comment by JesperSchulz** [comment]
I'm actually receving a little push back on exposing funtions in COD1297, because you should be using the new native al types like HttpRequestMessage, etc. Do those types not meet your needs? And if not, could you tell us what is missing?

**Comment by SjoerddeClippelaar** [comment]
Thank you Jesper for your answer. I think we will have enough when we request a InStream response. At the moment we are trying to reduce the dotnet in our current BC1401 version and going to AL at the same time.

**Comment by JesperSchulz** [comment]
Sorry, just to be clear here... What would you like me to expose in COD1297? Imagine everything can't be used for extensions right now, which functions would you like us to expose and how would you use them together with the al native types? Just want to make sure we're not misunderstanding each other and you will be hoping for code changes you won't get :-)

**Comment by JesperSchulz** [comment]
Will look into your requests next week. Have a lovely weekend! :-)

**Comment by SjoerddeClippelaar** [comment]
No please. You already helped me enough for now exposing ProcessFaultJsonResponse. Have a great weekend!
