### ISSUE TITLE
E-mail sender name is not set

### ISSUE THREAD

**Issue by LutzRose** [microsoft/cal-open-library#130]
CodeUnit 3031 "DotNet_SmtpMessage" overwrites the internal property FromAddress with the function SetFromName.

```AL
[External]
PROCEDURE SetFromName@3(FromName@1000 : Text);
BEGIN
  DotNetSmtpMessage.FromAddress := FromName;
END;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting! Will fix that right away.
