### ISSUE TITLE
SOAP codeunit transfer files with BigText/Base64

### ISSUE THREAD

**Issue by thomasdynalogic** [Microsoft/cal-open-library#22]
To transfer files from and to NAV with SOAP web service, we use a parameter of type "BigText".
In the NAV function we uses dotnet to write to OutStream. Suggestion to make 2 cal-open-library funtions to handle this. Please read this post descriping how-to. Please read all comments in the post.
[Kauffmann - Binary data with NAV Web Service](https://www.kauffmann.nl/2012/04/04/binary-data-with-nav-web-service/)

**Comment by JesperSchulz** [comment]
If you would like add 2 library functions, please provide the code in a pull request. We will happily consider your contribution and add it to our base application, if it qualifies as an open C/AL library function.
