### ISSUE TITLE
Custom. NET code

### ISSUE THREAD

**Issue by Gallimathias** [Microsoft/cal-open-library#4]
Is it allowed to submit wrappers with own. NET library?

**Comment by StanislawStempin** [comment]
No, sorry, only wrappers for the standard .NET libraries.

**Comment by Gallimathias** [comment]
Ok, that's a pity :(. I would have started to submit a lot of nice little tools now. Maybe. sometime somewhere else

**Comment by doctorpartlow** [comment]
> Ok, that's a pity :(. I would have started to submit a lot of nice little tools now. Maybe. sometime somewhere else

@Gallimathias, can that somewhere else be my email inbox?

**Comment by Gallimathias** [comment]
If I make such a thing available then for all open source. We could start an alternative own SDK and / or open library without MS.

feel free to write me a mail.

Marcus.Aurelius@gallimathias.de

For more plans see here:   [Microsoft/AL/#478](https://github.com/Microsoft/AL/issues/478)
