### ISSUE TITLE
Decompress XmlStream with XmlDictionaryReader.CreateMtomReader

### ISSUE THREAD

**Issue by megel** [Microsoft/cal-open-library#47]
For some resons I need the functionallity of *XmlDictionaryReader.CreateMtomReader* to decompress a response stream from a http-call. 

The **C/Side** method could look like this:

```javascript
[External] DecompressStreamToXmlStream(VAR CompressedStream : InStream;VAR XmlStream : InStream;ContentType : Text)
GZipStream := GZipStream.GZipStream(CompressedStream, CompressionMode.Decompress);
DotNetArray := DotNetArray.CreateInstance(GETDOTNETTYPE(TextEncoding),1);
DotNetArray.SetValue(TextEncoding.UTF8,0);
XmlDictionaryReader := XmlDictionaryReader.CreateMtomReader(GZipStream,DotNetArray, ContentType, XmlDictionaryReaderQuotas.Max);
XmlDictionaryReader.MoveToContent();

XmlDocument := XmlDocument.XmlDocument();
XmlDocument.PreserveWhitespace := TRUE;
XmlDocument.Load(XmlDictionaryReader);
MemoryStream := MemoryStream.MemoryStream;
XmlDocument.Save(MemoryStream);
MemoryStream.Position := 0;
XmlStream := MemoryStream;

```

The **Microsoft/AL** method could be:
```javascript
local procedure ReadContent(var Response: HttpResponseMessage; var Xml: XmlDocument);
var ContentType: Text;
    CU: Codeunit "Stream Management";
    HttpStream: InStream;
    XmlStream:  InStream;
begin
    Response.Content.ReadAs(HttpStream);
    ContentType := '...';
    CU.DecompressStreamToXmlStream(HttpStream, XmlStream, ContentType);
    XmlDocument.ReadFrom(XmlStream, Xml);        
end;
```

@JesperSchulz, do you have some recommendations for my questions:

1) Where should I add this method?
1) Is this signature correct? 
1) How can I get the ContentType from HttpResponseMethod?

**Comment by JesperSchulz** [comment]
Sorry about the very late reply! It's been a little hectic the past couple of days :-) But let me try to answer your questions:
1) If in doubt, just create a new codeunit which only contains your added functions. We'll then find a proper home for the new function(s) when porting the code to our BaseApp.
2) The signature looks good to me!
3) Directly from the response headers: httpResponseMessage.Content.Headers[“Content-Type”]

If you create a pull request, I'll try to get your code in in time for the February update. Remember also to add a few tests, which ensure that the functions work as you'd like them to. Thanks a lot for your contribution and sorry again for the long wait.

**Comment by megel** [comment]
@JesperSchulz, I have created the pull request for the file. The test is a little bit difficult - I have to rebuild some logic from the Server component.

**Comment by JesperSchulz** [comment]
Great! I'll try to get your changes in before Christmas!

**Comment by JesperSchulz** [comment]
I'll close this issue, as we'll track changes in your new pull request #48.
