### ISSUE TITLE
MemoryStream wrapper - function visbility

### ISSUE THREAD

**Issue by mrabus** [Microsoft/cal-open-library#51]
Hello Dev Team,

I was trying to migrate some code from C/AL to new AL language, but unfortunately my old code uses .NET class MemoryStream. 

So I tried to use the new wrapper codeunit 704. But when I try that, i have some issues:
![grafik](https://user-images.githubusercontent.com/2485163/34395273-3a815b3c-eb5f-11e7-85a0-97237c03cf59.png)

![grafik](https://user-images.githubusercontent.com/2485163/34395302-6c49657e-eb5f-11e7-943c-15bb98d9984a.png)

Well, I checked the codeunit and none of the functions have FunctionVisiblity = External. I am using the latest (german) developer preview. Is there a way around that or can you please make the functions accessible for extension development?

Thanks and keep on the good work, guys! 

The issue has been moved from Microsoft/AL to the cal-open-library; a workaround could be to set the app target to internal

**Comment by JesperSchulz** [comment]
That's a mistake from our side! The functions should obviously be external. I will fix that right away and the changes will be rolled out with the February update. Docker images will contain the fixes sooner.
Thanks for reporting and sorry about the inconvenience!

**Comment by JesperSchulz** [comment]
Changes pushed to repo through d48420258cac4000d003fb272a6246278a6361ae. Closing issue.

**Comment by mrabus** [comment]
No problem, thank you very much for the quick reaction!

**Comment by JesperSchulz** [comment]
The fix went into the depot this night and should be available through one of the upcoming docker images.
