### ISSUE TITLE
Error in the codeunit "6227 - Signed XML Mgt.".

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/cal-open-library#73]
The codeunit 6227 contains an error when checking a signed XML file. The check is only successful if the XML text passed does not contain any processing instructions. However, as soon as this contains an instruction, the check always fails. The error is in the following line:

`SignatureNode := XmlDocument.FirstChild.SelectSingleNode('xmlsig:Signature',XmlNamespaceManager);`

Due to the "FirstChild" property, finding the required XML node is only successful if no processing instruction is passed. This is because it is also to be regarded as a child. A correction should be made that enables both cases to be covered and thus a successful XML signature check to be performed.

This also requires an adjustment. In the function where you can create new signatures and return the text, you get an XML text file, which also does not contain any processing instructions. The file starts immediately with the root element.

**Comment by JesperSchulz** [comment]
Thanks for reporting! I'll make the author of the library aware of your findings and ask him to take a look. I'll also create a bug in our system to keep track of the issue. Thanks again!

**Comment by JesperSchulz** [comment]
Just for info: it's being looked into by anzwdev.

**Comment by JesperSchulz** [comment]
The issue was resolved :-) Thanks again for reporting!
