### ISSUE TITLE
Request secure random bytes

### ISSUE THREAD

**Issue by rdebath** [Microsoft/cal-open-library#74]
My current requirement is for a Type 4 GUID generated using a secure random number generator.

It is currently possible to indirectly call `RNGCryptoServiceProvider` through the `GeneratePassword` function in CU1267. But this returns a string that has been heavily processed, so to smooth it out I feed a long password through a hash from CU1266 and convert the returned hex to a text format GUID.

This is a little bit "Heath Robinson" so please would you add wrappers for `RNGCryptoServiceProvider` that return a requested number of bytes as hex or base64 and a third wrapper that returns a secure GUID.

**Comment by JesperSchulz** [comment]
Hi rdebath!

Thanks for your suggestion! Preferably, you would add the wrapper yourself in this repo by creating a pull request :-) For inspiration on how to write a wrapper, please refer to #67 or #70. You will find even more wrappers in the range COD3000 and up here in this repo. I look forward to receive a pull request with your desired functionality!
