### ISSUE TITLE
Request System.Drawing

### ISSUE THREAD

**Issue by Tobias-Gruber** [Microsoft/cal-open-library#77]
I wrote a library in C/AL to create QR Codes. I can create the Datamatrix without use of any DotNet Libraries. But in order to make an image out of this I need the System.Drawing Dll or any other library that allows it to draw within a Stream.

I'd be happy if you consider to include this.

Thanks
Tobias

**Comment by JesperSchulz** [comment]
Hi Tobias!

That sounds cool :) Preferably, you would add the wrapper yourself in this repo by creating a pull request :-) For inspiration on how to write a wrapper, please refer to #67 or #70. You will find even more wrappers in the range COD3000 and up here in this repo. I look forward to receive a pull request with your desired functionality! Have a great weekend!

/Jesper
